import {create} from "zustand";
export const useStore=create((set,get)=>({
  user:null,userProfile:null,setUser:u=>set({user:u}),setUserProfile:p=>set({userProfile:p}),
  vitals:{spo2:null,hr:null,temp:null,resp:null},vitalsHistory:[],
  setVitals:v=>{const ts={...v,timestamp:Date.now()};set(s=>({vitals:ts,vitalsHistory:[...s.vitalsHistory.slice(-500),ts]}));},
  alertStatus:"normal",activeAlerts:[],
  setAlertStatus:s=>set({alertStatus:s}),
  addAlert:a=>set(s=>({activeAlerts:[a,...s.activeAlerts.slice(0,49)]})),
  clearAlerts:()=>set({activeAlerts:[],alertStatus:"normal"}),
  connectedDevice:null,connectionType:null,
  setConnectedDevice:(d,t)=>set({connectedDevice:d,connectionType:t}),
  disconnect:()=>set({connectedDevice:null,connectionType:null}),
  reminders:[],setReminders:r=>{set({reminders:r});},
  toggleReminder:id=>{const u=get().reminders.map(r=>r.id===id?{...r,active:!r.active}:r);get().setReminders(u);},
  theme:"light",setTheme:t=>{set({theme:t})},
  profilePhoto:null,wallpaper:null,
  setProfilePhoto:u=>{set({profilePhoto:u})},
  setWallpaper:u=>{set({wallpaper:u})},
  messages:{},
  setMessages:(id,msgs)=>set(s=>({messages:{...s.messages,[id]:msgs}})),
  appendMessage:(id,msg)=>set(s=>({messages:{...s.messages,[id]:[...(s.messages[id]||[]),msg]}})),
  gpsLocation:null,setGpsLocation:loc=>set({gpsLocation:loc}),
  aiAnalysis:null,aiLoading:false,setAiAnalysis:a=>set({aiAnalysis:a}),setAiLoading:v=>set({aiLoading:v}),
  manualHistory:[],addManualVital:v=>{const e={...v,timestamp:Date.now(),source:"manual"};set(s=>({manualHistory:[e,...s.manualHistory.slice(0,99)]}));},
  loadPersistedData:async()=>{},
}));
